### PR TITLE
new exposure model, updates to all schema (no psra yet)

### PR DESCRIPTION
**Pull request by wkhchow**
**Notes**
- updated exposure model, now includes site level.  Site level indicators if available (physical exposure, DSRA, PSRA(_not yet implemented_))

- updates to all sql scripts for each schema to incorporate new exposure where applicable

**Source table**
- Create_table_canada_site_exposure.sql (new site level exposure data)

- Update_site_exposure_to_building.sql (updates site level to building level, this should be run after Create_table_canada_exposure.sql and Create_table_canada_site_exposure.sql)

**New Indicators**
- Create_physical_exposure_site_level_indicators_PhysicalExposure.sql (site level indicators)

- Create_scenario_risk_site_level_Indicators_ALL.sql (site level indicators)

 Will need to update add_data.sh to incorporate new sql scripts.  May want to test for any issues for stack build before merge.

### CODE REVIEW

**Review by jvanulde — APPROVED** [review]
Looks good to me.

**Comment by wkhchow** [comment]
Need to close PR for now pending new development/issues with site level exposure data and add new sql modified scripts.

**Comment by wkhchow** [comment]
**Notes**
- added CASCADE to all DROP TABLE/VIEWS if it was missing
- added aggregation id/names (pruid,prname,eruid,ername,cduid,cdname,csduid,csdname) to nhsl views (physical exposure, risk dynamics, social fabric, multi hazards)
- added separate set of sql files to run physical exposure/DSRA views if source files are based off site exposure data (ie Metro Van).  

**additional sql files for site related runs(_ste)**
- Create_table_canada_site_exposure_ste.sql
- Update_site_exposure_to_building_ste.sql
- Create_table_s_sitemesh_update_site_exposure_ste.sql
- Create_table_vs_30_BC_site_model_update_site_exposure_ste.sql
- Create_scenario_risk_site_level_Indicators_ALL_ste.sql
- Create_scenario_risk_building_Indicators_ALL_ste.sql
- Create_scenario_risk_sauid_Indicators_ALL.sql
- Create_physical_exposure_site_level_indicators_PhysicalExposure_ste.sql
- Create_physical_exposure_building_indicators_PhysicalExposure_ste.sql
- Create_physical_exposure_sauid_indicators_view_PhysicalExposure_ste.sql


2 sets of exposures with different workflow for each.  Previous workflow with just using the national building exposure layer remains unchanged.  Scenarios using the site (ie Metro Van) will need to run a separate set of sql scripts to get site/building/sauid results.

**site exposure layer (ie PhysExpRef_MetroVan_v4.csv)**
_Exposure (one time runs)_
- Create_table_canada_site_exposure_ste.sql
- Update_site_exposure_to_building_ste.sql
_Physical Exposure (one time runs)_
- Create_physical_exposure_site_level_indicators_PhysicalExposure_ste.sql
- Create_physical_exposure_building_indicators_PhysicalExposure_ste.sql
- Create_physical_exposure_sauid_indicators_view_PhysicalExposure_ste.sql



_ DSRA_
_ (one time run)_
- Create_table_vs_30_BC_site_model_update_site_exposure_ste.sql
_(run per scenario)_
- Create_table_s_sitemesh_update_site_exposure_ste.sql
- Create_scenario_risk_site_level_Indicators_ALL_ste.sql
- Create_scenario_risk_building_Indicators_ALL_ste.sql
- Create_scenario_risk_sauid_Indicators_ALL.sql

**Comment by jvanulde** [comment]
@drotheram have you reviewed?

**Comment by drotheram** [comment]
Yes, changes need to be made to opendrr-api before we can merge this branch to master

**Review by drotheram — APPROVED** [review]
Tested in integrate-new-exposure-model branch of opendrr-api

**Pull request merged**
